/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class profile extends javax.swing.JFrame {

    /**
     * Creates new form profile
     */
    
    
    int record_counter = 0;
    int record_navigator = 0;
    
    //Storages
     String Storage_Name[] = new String[100];
    String Storage_Age[] = new String[100];
    String Storage_Address[] = new String[100];
    String Storage_Birthday[] = new String[100];
    String Storage_ContactNumber[] = new String[100];
    String Storage_Email[] = new String[100];
    
    
    public profile() {
         initComponents();
        Enable_Inputfield(false);
        Enable_Save_Cancel(false);
        Enable_View(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BT_ADD = new javax.swing.JButton();
        BT_EDIT = new javax.swing.JButton();
        BT_VIEW = new javax.swing.JButton();
        BT_NEXT = new javax.swing.JButton();
        BT_PREVIOUS = new javax.swing.JButton();
        BT_SEARCH = new javax.swing.JButton();
        BT_DELETE = new javax.swing.JButton();
        BT_LAST = new javax.swing.JButton();
        BT_SAVE = new javax.swing.JButton();
        BT_BROWSE = new javax.swing.JButton();
        BT_CANCEL = new javax.swing.JButton();
        BT_FIRST = new javax.swing.JButton();
        BT_ENDVIEW = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtage = new javax.swing.JTextField();
        txtcontactnumber = new javax.swing.JTextField();
        txtbirthday = new javax.swing.JTextField();
        txtaddress = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PERSONAL INFORMATION SYSTEM");

        jPanel1.setBackground(new java.awt.Color(102, 255, 51));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        jLabel1.setText("PROFILE INFORMATION SYSTEM");

        jLabel2.setText("2X2 PICTURE");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        BT_ADD.setText("ADD");
        BT_ADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_ADDActionPerformed(evt);
            }
        });

        BT_EDIT.setText("EDIT");
        BT_EDIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_EDITActionPerformed(evt);
            }
        });

        BT_VIEW.setText("VIEW");
        BT_VIEW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_VIEWActionPerformed(evt);
            }
        });

        BT_NEXT.setText("NEXT");
        BT_NEXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_NEXTActionPerformed(evt);
            }
        });

        BT_PREVIOUS.setText("PREVIOUS");
        BT_PREVIOUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_PREVIOUSActionPerformed(evt);
            }
        });

        BT_SEARCH.setText("SEARCH");

        BT_DELETE.setText("DELETE");

        BT_LAST.setText("LAST");
        BT_LAST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_LASTActionPerformed(evt);
            }
        });

        BT_SAVE.setText("SAVE");
        BT_SAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_SAVEActionPerformed(evt);
            }
        });

        BT_BROWSE.setText("BROWSE");

        BT_CANCEL.setText("CANCEL");
        BT_CANCEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_CANCELActionPerformed(evt);
            }
        });

        BT_FIRST.setText("FIRST");
        BT_FIRST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_FIRSTActionPerformed(evt);
            }
        });

        BT_ENDVIEW.setText("ENDVIEW");
        BT_ENDVIEW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_ENDVIEWActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel3.setText("NAME:");

        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });

        txtcontactnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcontactnumberActionPerformed(evt);
            }
        });

        txtaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaddressActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel4.setText("BIRTHDAY:");

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel5.setText("CONTACT NUMBER:");

        jLabel6.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel6.setText("EMAIL:");

        jLabel7.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel7.setText("ADDRESS:");

        jLabel8.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel8.setText("AGE:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BT_DELETE)
                        .addGap(78, 78, 78))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(BT_ADD)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BT_EDIT)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BT_VIEW))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(BT_SAVE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BT_CANCEL)
                                        .addGap(20, 20, 20)
                                        .addComponent(BT_ENDVIEW)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BT_NEXT)
                                    .addComponent(BT_FIRST)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BT_PREVIOUS)
                                .addGap(18, 18, 18)
                                .addComponent(BT_SEARCH))
                            .addComponent(BT_LAST)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtbirthday, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtcontactnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(BT_BROWSE)
                                        .addGap(12, 12, 12))))
                            .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtbirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BT_BROWSE)
                    .addComponent(txtcontactnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BT_ADD, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT_EDIT, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT_VIEW, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT_NEXT, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT_PREVIOUS, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT_SEARCH, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BT_SAVE, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT_CANCEL, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT_ENDVIEW, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT_FIRST, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT_LAST, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT_DELETE, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaddressActionPerformed

    private void txtcontactnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcontactnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcontactnumberActionPerformed

    private void BT_ADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_ADDActionPerformed
        // TODO add your handling code here:
        Enable_Inputfield(true);
        Enable_Save_Cancel(true);
    }//GEN-LAST:event_BT_ADDActionPerformed

    private void BT_EDITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_EDITActionPerformed
        // TODO add your handling code here:
        Enable_Inputfield(true);
        Enable_Save_Cancel(true);
    }//GEN-LAST:event_BT_EDITActionPerformed

    private void BT_SAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_SAVEActionPerformed
        // TODO add your handling code here:
        Enable_Inputfield(false);
        Enable_Save_Cancel(false);
        Store_Record(record_counter);
        record_counter++;
    }//GEN-LAST:event_BT_SAVEActionPerformed

    private void BT_CANCELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_CANCELActionPerformed
        // TODO add your handling code here:
        Enable_Inputfield(false);
        Enable_Save_Cancel(false);
    }//GEN-LAST:event_BT_CANCELActionPerformed

    private void BT_VIEWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_VIEWActionPerformed
        // TODO add your handling code here:
          Enable_View(true);
          record_navigator = 0;
          View_Record(record_navigator);
          
    }//GEN-LAST:event_BT_VIEWActionPerformed

    private void BT_NEXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_NEXTActionPerformed
        // TODO add your handling code here:
        Enable_View(true);
        Enable_Inputfield(false);
        record_navigator++;
        View_Record(record_navigator);
        
    }//GEN-LAST:event_BT_NEXTActionPerformed

    private void BT_PREVIOUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_PREVIOUSActionPerformed
        // TODO add your handling code here:
        record_navigator--;
        View_Record(record_navigator);
        
    }//GEN-LAST:event_BT_PREVIOUSActionPerformed

    private void BT_ENDVIEWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_ENDVIEWActionPerformed
        // TODO add your handling code here:
        Enable_View(false);
    }//GEN-LAST:event_BT_ENDVIEWActionPerformed

    private void BT_FIRSTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_FIRSTActionPerformed
        // TODO add your handling code here:
        record_navigator = 0;
        View_Record(record_navigator);
        
    }//GEN-LAST:event_BT_FIRSTActionPerformed

    private void BT_LASTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_LASTActionPerformed
        // TODO add your handling code here:
        record_navigator = record_counter - 1;
        View_Record(record_navigator);
    }//GEN-LAST:event_BT_LASTActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_ADD;
    private javax.swing.JButton BT_BROWSE;
    private javax.swing.JButton BT_CANCEL;
    private javax.swing.JButton BT_DELETE;
    private javax.swing.JButton BT_EDIT;
    private javax.swing.JButton BT_ENDVIEW;
    private javax.swing.JButton BT_FIRST;
    private javax.swing.JButton BT_LAST;
    private javax.swing.JButton BT_NEXT;
    private javax.swing.JButton BT_PREVIOUS;
    private javax.swing.JButton BT_SAVE;
    private javax.swing.JButton BT_SEARCH;
    private javax.swing.JButton BT_VIEW;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtbirthday;
    private javax.swing.JTextField txtcontactnumber;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables


public void Enable_Inputfield(boolean field)
{
    txtname.setEnabled(field);
    txtage.setEnabled(field);
    txtaddress.setEnabled(field);
    txtbirthday.setEnabled(field);
    txtcontactnumber.setEnabled(field);
    txtemail.setEnabled(field);
}

public void Enable_Save_Cancel(boolean save)
{
    BT_ADD.setEnabled(!save);
    BT_EDIT.setEnabled(!save);
    
    BT_SAVE.setEnabled(save);
    BT_CANCEL.setEnabled(save);
    BT_BROWSE.setEnabled(save);
}

public void Enable_View(boolean enable )
{
    BT_VIEW.setEnabled(!enable);
    
    BT_ENDVIEW.setEnabled(enable);
    BT_NEXT.setEnabled(enable);
    BT_PREVIOUS.setEnabled(enable);
    BT_LAST.setEnabled(enable);
    BT_FIRST.setEnabled(enable);
    BT_SEARCH.setEnabled(enable);
    BT_DELETE.setEnabled(enable);
    
}

public void Store_Record(int store)
{
Storage_Name[store] = txtname.getText();
Storage_Age[store] =  txtage.getText();
Storage_Address[store] = txtaddress.getText();
Storage_Birthday[store] = txtbirthday.getText();
Storage_ContactNumber [store] = txtcontactnumber.getText();
Storage_Email[store] = txtemail.getText();
}

public void View_Record(int view)
{
  txtname.setText(Storage_Name[view]);
  txtage.setText(Storage_Age[view]);
  txtaddress.setText(Storage_Address[view]);
  txtbirthday.setText(Storage_Birthday[view]);
  txtcontactnumber.setText(Storage_ContactNumber[view]);
  txtemail.setText(Storage_Email[view]);
  
}

}

